type: simple_ar
model:
  type: simple_ar
  duration: 256
  max_tokens: 896
  pitch_range: [21, 109]
  dim: 512
  num_layers: 8
  max_note_duration: 64
training:
  seed: 0x517
  batch_size: 16
  accum_batches: 1
  shuffle: true
  drop_last: true
  gradient_clip_val: null
  precision: "16-mixed"
  demo_samples: 1

  lr: 0.0001
  betas: [0.9, 0.999]
  eps: 1e-8
  weight_decay: 0

  demo_steps: 500
  checkpoint_steps: 50000
  max_steps: 1000000
