type: vae
model:
  type: vae
  duration: 32
  test_duration: 256
  max_tokens: 160
  pitch_range: [21, 109]
  max_note_duration: 63
  encoder:
    dim: 512
    num_layers: 5
  decoder:
    dim: 512
    num_layers: 5
  bottleneck:
    type: "vae"
    vae_params:
      beta: 0.1
      latent_dim: 256
      beta_cycle_steps: 50000
      beta_start_step: 1000
training:
  seed: 0x517
  batch_size: 32
  accum_batches: 1
  shuffle: true
  drop_last: true
  gradient_clip_val: null
  precision: "16-mixed"
  demo_samples: 1

  lr: 0.0001
  betas: [0.9, 0.999]
  eps: 1e-8
  weight_decay: 0

  demo_steps: 5000
  checkpoint_steps: 100000
  max_steps: 1000000
